// Mocks generated by Mockito 5.4.2 from annotations
// in tasks_riverpod/test/mock/presentation/viewmodel/tasklist/task_list_viewmodel_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:state_notifier/state_notifier.dart' as _i9;
import 'package:tasks_riverpod/domain/model/task.dart' as _i7;
import 'package:tasks_riverpod/domain/model/task_id.dart' as _i8;
import 'package:tasks_riverpod/domain/model/tasks_list.dart' as _i6;
import 'package:tasks_riverpod/presentation/state/state.dart' as _i2;
import 'package:tasks_riverpod/presentation/viewmodel/taskslist/task_list_viewmodel.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeState_0<T> extends _i1.SmartFake implements _i2.State<T> {
  _FakeState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TaskListViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskListViewModel extends _i1.Mock implements _i3.TaskListViewModel {
  MockTaskListViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onError(_i4.ErrorListener? _onError) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          _onError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);

  @override
  _i5.Stream<_i2.State<_i6.TaskList>> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i2.State<_i6.TaskList>>.empty(),
      ) as _i5.Stream<_i2.State<_i6.TaskList>>);

  @override
  _i2.State<_i6.TaskList> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeState_0<_i6.TaskList>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.State<_i6.TaskList>);

  @override
  set state(_i2.State<_i6.TaskList>? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.State<_i6.TaskList> get debugState => (super.noSuchMethod(
        Invocation.getter(#debugState),
        returnValue: _FakeState_0<_i6.TaskList>(
          this,
          Invocation.getter(#debugState),
        ),
      ) as _i2.State<_i6.TaskList>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  dynamic completeTask(_i7.Task? task) => super.noSuchMethod(Invocation.method(
        #completeTask,
        [task],
      ));

  @override
  dynamic undoTask(_i7.Task? task) => super.noSuchMethod(Invocation.method(
        #undoTask,
        [task],
      ));

  @override
  dynamic addTask(
    String? title,
    String? description,
    bool? isCompleted,
    DateTime? dueDate,
  ) =>
      super.noSuchMethod(Invocation.method(
        #addTask,
        [
          title,
          description,
          isCompleted,
          dueDate,
        ],
      ));

  @override
  dynamic updateTask(_i7.Task? newTask) => super.noSuchMethod(Invocation.method(
        #updateTask,
        [newTask],
      ));

  @override
  dynamic deleteTask(_i8.TaskId? id) => super.noSuchMethod(Invocation.method(
        #deleteTask,
        [id],
      ));

  @override
  bool updateShouldNotify(
    _i2.State<_i6.TaskList>? old,
    _i2.State<_i6.TaskList>? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.RemoveListener addListener(
    _i9.Listener<_i2.State<_i6.TaskList>>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
      ) as _i4.RemoveListener);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
